CREATE TABLE IF NOT EXISTS packages (
  id SERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  price VARCHAR(50) NOT NULL,
  duration VARCHAR(50) NOT NULL,
  recommended BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);
